### ISSUE TITLE
New Package: Remote Server for Laravel Pulse

### ISSUE THREAD

**Issue by tobiasvielmetter** [timwassenburg/awesome-pulse#3]
https://github.com/wrklst/pulse-remote-server.git

Add remote linux server to your server stats. This is meant for servers that do not run PHP, e.g. database or cache servers. Servers that run PHP should install their own instance of [Laravel Pulse](https://pulse.laravel.com/) instead.

**Comment by timwassenburg** [comment]
Hey, I have added it, thanks!
