### ISSUE TITLE
Redis monitoring package

### ISSUE THREAD

**Issue by Flythe** [timwassenburg/awesome-pulse#4]
Hey Tim, thank you for curating this list of Pulse packages!

We've developed a [Redis card](https://github.com/PraatmetdeDokter/pulse-redis-monitor) that monitors usage by parsing the Redis INFO command. If you think it suits the list, please feel free to add it.

**Comment by timwassenburg** [comment]
Hey Allard, sorry for the late response, I forgot about it. 

Thanks for submitting your Redis card, I have added it to the list!
