### ISSUE TITLE
New package: API layer for Pulse metrics

### ISSUE THREAD

**Issue by robertogallea** [timwassenburg/awesome-pulse#6]
Hi Tim,
I just published this package for adding an API layer to Pulse metrics: https://github.com/robertogallea/pulse-api

What about it?

**Comment by robertogallea** [comment]
This could be useful for embedding Pulse information outside of the host application or do a complete customization of the official Pulse dashboard

**Comment by timwassenburg** [comment]
Hi Roberto, it looks like an interesting package. I'm not entirely sure which category it would fit best into, do you have any ideas?

**Comment by robertogallea** [comment]
Well, I don't think it does fit any of the current categories (it is not a card, it is not a tutorial or anything else listed). Perhaps you could add something like _Extensions_? How does it sound to you?

**Comment by timwassenburg** [comment]
Sounds like a good solution to me, I've added it to the list!
