### ISSUE TITLE
New card: database size 

### ISSUE THREAD

**Issue by robertogallea** [timwassenburg/awesome-pulse#7]
The package https://github.com/robertogallea/pulse-db-size adds a recorder and a card to collect and display database size. The card shows the total size, the number of tables and for each table the individual size is shown too, along with a bar chart showing the size percentage w.r.t. the total size. Configurable parameters are the following :

- database connection to query the table size to
- throttling delay between two queries

![Pulse DB Size Card](https://github.com/robertogallea/pulse-db-size/blob/70233bd488b477086c101c093ffe6fcbbbd904f8/images/img.png)

**Comment by timwassenburg** [comment]
Thanks for the suggestion, it's on the list.
